# -*- coding: utf-8 -*-
"""WineQuality-Red-Regration-ANN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/145KCS-7VhlZsC7j7k90Bf-FG20JTab7h
"""

import pandas as pd
data = pd.read_csv("winequality-red.csv", delimiter=';')



import sklearn
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

scale = MinMaxScaler()
data = pd.DataFrame(scale.fit_transform(data))

y = data[11]
x = data.drop(columns=[11])

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)

import keras
from keras.models import Sequential
from keras.layers import Dense
from keras import metrics

model = Sequential()

model.add(Dense(32 , input_dim = 11, activation = 'relu'))
model.add(Dense(32 , activation = 'relu'))
model.add(Dense(7 , activation = 'linear'))

model.compile(optimizer="Adam" , loss="mean_squared_error", metrics=["accuracy"])

output = model.fit(x_train, y_train, epochs = 250, verbose = 1)

y_pred = model.predict(x_test)
score = model.evaluate(x_test, y_test, verbose = 0)
score[0]





